### ISSUE TITLE
Can object be cached in chunks by multiple modes!

### ISSUE THREAD

**Issue by innerop** [NVIDIA/dfcpub#63]
Trying to understand how this works compared to MongoDB’s GridFS. I understand it’s a cache for objects stored in cloud buckets like S3 et al so my question is if an object is larger in size than the disk space allocated for this on each node will the object be stored using multiple nodes?

Where in the docs can I find a simple explanation of how this works?

**Comment by VirrageS** [comment]
Nope, for now we don't support storing object on multiple nodes - as we expect that the disks will be much more spacious than any of the object.

Nevertheless, it is something that is on our 'todo' list. Not because space but performance. Performance is the key in this project and chunking object into smaller ones gives a chance to stream the object from multiple nodes/disks which can result in linear speedup (without that we are only constrained by the single disk speed).
